ktor:
    development: true
    application:
        modules:
            - io.ktor.chat.RootModuleKt.rootModule
            - io.ktor.chat.DatabasesKt.databaseModule
            - io.ktor.chat.RepositoriesKt.repositoriesModule
            - io.ktor.chat.AuthenticationKt.sessionCookieModule
            - io.ktor.chat.RoutingKt.routingModule
    deployment:
        port: 8080
        watch:
            - build/classes
            - build/processedResources

security:
    secret: S3crE4_P@55w0Rd

database:
    main:
        url: "jdbc:h2:file:./db/db"
        user: root
        driver: org.h2.Driver
        password: ""
